# Generated by Django 2.1.5 on 2019-02-22 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_info',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='checkout.BillingInformation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_info',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='checkout.PaymentInformation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_info',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='checkout.ShippingInformation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='user.User'),
        ),
    ]
