# Generated by Django 2.1.5 on 2019-02-22 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20190222_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='checkout.BillingInformation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='checkout.PaymentInformation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='checkout.ShippingInformation'),
        ),
    ]
