# Generated by Django 2.1.5 on 2019-02-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190219_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='apt_number',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street_number',
        ),
        migrations.AddField(
            model_name='address',
            name='address1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='address2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
